name: WebPImageConverter

on:
  push:

permissions:
  contents: write

jobs:
  php74:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up PHP v7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: gd, imagick, mbstring, zip, intl

      - name: Install Composer
        run: composer install

      - name: Linting
        run: composer run lint

      - name: Static Analysis
        run: composer run analyse

      - name: Testing
        run: composer run test

  php80:
    runs-on: ubuntu-latest

    needs: php74

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up PHP v8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: gd, imagick, mbstring, zip, intl

      - name: Install Composer
        run: composer install

      - name: Linting
        run: composer run lint

      - name: Static Analysis
        run: composer run analyse

      - name: Testing
        run: composer run test

  php82:
    runs-on: ubuntu-latest

    needs: php80

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up PHP v8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd, imagick, mbstring, zip, intl

      - name: Install Composer
        run: composer install

      - name: Linting
        run: composer run lint

      - name: Static Analysis
        run: composer run analyse

      - name: Testing
        run: composer run test

  build:
    runs-on: ubuntu-latest

    needs: php82

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Checkout to Master Built
      if: github.ref == 'refs/heads/master'
      env:
        USER_EMAIL: "badasswpdev@gmail.com"
        USER_NAME: "badasswp"
      run: |
        git config user.email "${USER_EMAIL}"
        git config user.name "${USER_NAME}"
        git checkout -b master-built

    - name: Build Vendor folder
      run: |
        composer install --no-dev
        git add vendor/ -f
        git rm composer.json

    - name: Clean Up Files
      run: |
        while IFS= read -r file; do
          git rm -r "$file"
        done < .deployignore
        git rm .deployignore
        git clean -f composer.lock

    - name: Push to Master Built
      run: |
        git commit -m "push to master-built"
        git push origin master-built -f
        rm -rf .git
